services:
  - type: web
    name: dressmaster-api
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromSecret: DATABASE_URL
      - key: JWT_SECRET
        fromSecret: JWT_SECRET
      - key: PORT
        value: 3000
    healthCheckPath: /health
